# Generated by Django 6.0.2 on 2026-02-09 15:04

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Club Name")),
                ("location", models.CharField(max_length=150, verbose_name="Location")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "is_organizer",
                    models.BooleanField(default=False, verbose_name="Is Organizer?"),
                ),
                (
                    "acp_club_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="ACP Code",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Is Active?"),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("ACP", "Audax Club Parisien"),
                            ("LRM", "Les Randonneurs Mondiaux"),
                            ("NAT", "National Federation-representative"),
                        ],
                        default="NAT",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Country"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Event Name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL friendly name, ej: madrid-gijon-2026",
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("BRM", "BRM (200-1000km)"),
                            ("BRM_S", "BRM Special"),
                            ("LRM", "LRM (+1200km)"),
                            ("PBP", "Paris-Brest-Paris"),
                            ("SR600", "Super Randonnée (600km/10k)"),
                            ("FLECHE", "Flèche"),
                            ("OTHER", "Other"),
                        ],
                        default="BRM",
                        max_length=10,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(db_index=True, verbose_name="Year"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "distance_km",
                    models.PositiveIntegerField(verbose_name="Distance (km)"),
                ),
                (
                    "elevation_gain",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Elevation (m)"
                    ),
                ),
                ("location", models.CharField(max_length=150, verbose_name="Location")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                ("official_link", models.URLField(blank=True)),
                (
                    "organizing_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to="core.club",
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="club",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs",
                to="core.organization",
                verbose_name="Affiliated Organization",
            ),
        ),
        migrations.CreateModel(
            name="Randonneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "is_claimed",
                    models.BooleanField(
                        default=False,
                        help_text="Has the real user claimed this profile?",
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("PUB", "Public"),
                            ("COM", "Community Only"),
                            ("PRI", "Private"),
                        ],
                        default="PUB",
                        max_length=3,
                    ),
                ),
                ("strava_link", models.URLField(blank=True)),
                ("instagram_link", models.URLField(blank=True)),
                ("other_link", models.URLField(blank=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.club",
                        verbose_name="Current Club",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="randonneur_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Randonneur",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SR", "Super Randonneur"),
                            ("R5000", "Randonneur 5000"),
                            ("R10000", "Randonneur 10000"),
                            ("PBP", "PBP Finisher"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "issuing_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                    ),
                ),
                (
                    "randonneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="core.randonneur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FIN", "Finisher"),
                            ("DNF", "Did Not Finish"),
                            ("DNS", "Did Not Start"),
                            ("OT", "Over Time"),
                        ],
                        default="FIN",
                        max_length=5,
                    ),
                ),
                (
                    "time",
                    models.DurationField(
                        blank=True, help_text="Tiempo total (HH:MM)", null=True
                    ),
                ),
                (
                    "homologation_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.event",
                    ),
                ),
                (
                    "randonneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.randonneur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result",
                "ordering": ["time"],
            },
        ),
        migrations.AddIndex(
            model_name="randonneur",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="core_randon_last_na_4a9c43_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="result",
            unique_together={("randonneur", "event")},
        ),
    ]
