# Generated by Django 6.0.2 on 2026-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_result_homologation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_time_override",
            field=models.DurationField(
                blank=True,
                help_text="Override standard limit if needed (e.g. for LRM Al-Andalus 200h) (HH:MM:SS)",
                null=True,
                verbose_name="Custom Time Limit",
            ),
        ),
    ]
