# Generated by Django 6.0.2 on 2026-07-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event_max_time_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_time_override",
            field=models.DurationField(
                blank=True,
                help_text="Override standard limit if needed (e.g. for LRM Al-Andalus 200h) (HH:MM)",
                null=True,
                verbose_name="Custom Time Limit",
            ),
        ),
    ]
