# Generated by Django 6.0.2 on 2026-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_event_max_time_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Region"
            ),
        ),
    ]
