# Generated by Django 6.0.2 on 2026-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_club_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("an", "Andalucía"),
                    ("ar", "Aragón"),
                    ("as", "Asturias"),
                    ("ba", "Islas Baleares"),
                    ("cn", "Canarias"),
                    ("cb", "Cantabria"),
                    ("cl", "Castilla y León"),
                    ("cm", "Castilla-La Mancha"),
                    ("ca", "Cataluña"),
                    ("vl", "Comunidad Valenciana"),
                    ("ex", "Extremadura"),
                    ("ga", "Galicia"),
                    ("ma", "Madrid"),
                    ("mu", "Región de Murcia"),
                    ("na", "Navarra"),
                    ("va", "País Vasco"),
                    ("lo", "La Rioja"),
                ],
                max_length=100,
                null=True,
                verbose_name="Region",
            ),
        ),
    ]
