# Generated by Django 6.0.2 on 2026-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_club_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="randonneur",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
