# Generated by Django 6.0.2 on 2026-07-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_randonneur_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="parent_series",
            field=models.ForeignKey(
                blank=True,
                help_text="Override standard limit if needed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editions",
                to="core.event",
                verbose_name="Parent Series",
            ),
        ),
    ]
