# Generated by Django 6.0.2 on 2026-07-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_event_parent_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SR", "Super Randonneur"),
                    ("R5000", "Randonneur 5000"),
                    ("R10000", "Randonneur 10000"),
                    ("PBP", "PBP Finisher"),
                    ("LEPERTEL", "Challenge Lepertel"),
                ],
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
