# Generated by Django 6.0.2 on 2026-07-29 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_achievement_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SR", "Super Randonneur"),
                    ("R5000", "Randonneur 5000"),
                    ("R10000", "Randonneur 10000"),
                    ("PBP", "PBP Finisher"),
                    ("LEPERTEL", "Challenge Lepertel (LRM)"),
                ],
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="MergeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "duplicate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_requests_as_duplicate",
                        to="core.randonneur",
                        verbose_name="Duplicate Profile (To merge)",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_requests_as_master",
                        to="core.randonneur",
                        verbose_name="Master Profile (Destination)",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_merge_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merge Request",
                "verbose_name_plural": "Merge Requests",
                "unique_together": {("master", "duplicate")},
            },
        ),
    ]
