# Generated by Django 6.0.2 on 2026-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_achievement_kind_mergerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SR", "Super Randonneur"),
                    ("R5000", "Randonneur 5000"),
                    ("R10000", "Randonneur 10000"),
                    ("PBP", "PBP Finisher"),
                    ("LEPERTEL", "Challenge Lepertel (LRM)"),
                    ("SR10", "10x Super Randonnee Challenge"),
                    ("SR20", "20x Super Randonnee Challenge"),
                    ("SR30", "30x Super Randonnee Challenge"),
                ],
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
