# Generated by Django 6.0.2 on 2026-08-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_result_homologation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                help_text="URL friendly name, ej: madrid-gijon-2026",
                max_length=255,
                unique=True,
            ),
        ),
    ]
